eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8001/eureka/
server:
    port: 8005
spring:
    application:
        name: service-feign
feign:
    httpclient:
        enabled: true
    hystrix:
        enabled: true
